services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: vprocontainers/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  watchtower:
    image: nickfedor/watchtower:1.21.0
    restart: unless-stopped
    environment:
      REPO_USER: "${GHCR_USERNAME}"
      REPO_PASS: "${GHCR_TOKEN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --debug vproapp

  vproapp:
    image: ghcr.io/duytechie/actionprofile:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    container_name: vproapp
    ports:
      - "8080:8080"
    depends_on:
      - vprodb
      - vprocache01
      - vpromq01

  vproweb:
    build:
      context: ./Docker-files/web
    image: vprocontainers/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp

volumes:
  vprodbdata: {}
