name: Build WF
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  ECR_REPOSITORY: "vprofile-app-image"

permissions:
  contents: read
  packages: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # number of commits to fetch. 0 means fetch all

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if Build Fails
        if: failure()
        run: echo "Build job failed! Please check logs."

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

  Security_Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: json
          # exit-code:
          # 0 : continue if vulnerabilities are found
          # 1 : the workflow will be failed if vulnerabilities are found
          exit-code: 0
          vuln-type: os,library
          output: trivy-results.json
          # trivy-config: trivy.yaml

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json

  # BUILD_AND_PUBLISH:
  #   name: BUILD_AND_PUBLISH
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: [Build, Testing, Security_Scan]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Code checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ vars.AWS_REGION }}
  #
  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v2
  #
  #     - name: Build, tag, and push image to Amazon ECR
  #       id: build-image
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         IMAGE_TAG: ${{ github.sha }}
  #       run: |
  #         docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  BUILD_AND_PUBLISH:
    name: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    environment: ghcr
    needs: [Build, Testing, Security_Scan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_KEY }}

      - name: Build and push Docker image to GHCR
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        run: |
          docker build -f Docker-files/app/multistage/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
